name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD }}
      working-directory: ubuntu2204
      run: |
        packer build -var 'version=0.1.0' box-config.json
